version: '2'
services:
  runner0:
    image: ynm3k:latest
    restart: always
    volumes:
      - .:/code
    ports:
      - "127.0.0.1:10000:80"
  runner1:
    image: ynm3k:latest
    restart: always
    volumes:
      - .:/code
    ports:
      - "127.0.0.1:10001:80"
  runner2:
    image: ynm3k:latest
    restart: always
    volumes:
      - .:/code
    ports:
      - "127.0.0.1:10002:80"
  runner3:
    image: ynm3k:latest
    restart: always
    volumes:
      - .:/code
    ports:
      - "127.0.0.1:10003:80"
  runner4:
    image: ynm3k:latest
    restart: always
    volumes:
      - .:/code
    ports:
      - "127.0.0.1:10004:80"
  runner5:
    image: ynm3k:latest
    restart: always
    volumes:
      - .:/code
    ports:
      - "127.0.0.1:10005:80"
